---
# tasks file for ntp
- name: ensure ntp is installed
  yum:
    name: ntp
    state: present
  tags:
    - ntp
    - ntp_install

- name: configure ntp
  template:
    src: ntp.conf.j2
    dest: /etc/ntp.conf
    owner: root
    group: root
    mode: 0644
  tags:
    - ntp
    - ntp_configure
  notify:
      - restart ntpd

- name: ensure ntpd is running and enabled
  service:
    name: ntpd
    enabled: yes
    state: started
  tags:
    - ntp
    - ntp_started

